### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by encelo** [nCine/ncTiledViewer#1]
Some of the points on my to-do list are the following:

- [ ] Add a camera parent node to pan, zoom, and rotate a map
- [ ] Support more maps from [`tiled/examples`](https://github.com/mapeditor/tiled/tree/master/examples) (hexagonal, isometric)
- [ ] Add support for diplaying [image layers](https://doc.mapeditor.org/en/stable/manual/layers/#image-layers)
- [ ] Add support for `base64` decoding and `zlib` decompression
- [ ] Consider parsing the remaining elements of the [TMX Map Format](https://doc.mapeditor.org/en/stable/reference/tmx-map-format/)
